Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать,
что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по¶
каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в
нем должно быть 2 элемента.


In [2]:
import numpy as np

In [3]:
a_t = np.array([[1, 2, 3, 3, 1],
               [6, 8, 11, 10, 7]])
a = a_t.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
men_a = np.mean(a, axis=0)
men_a

array([2. , 8.4])

Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.



In [5]:
a_centered = a - men_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.



In [6]:
s1 = a_centered[0:,0]
s2 = a_centered[0:,1]
print(s1)
print(s2)

[-1.  0.  1.  1. -1.]
[-2.4 -0.4  2.6  1.6 -1.4]


In [7]:
a_centered_sp = s1.dot(s2)
print('Скаларное произведение признаков', a_centered_sp)

Скаларное произведение признаков 8.0


In [8]:
N = a_centered.shape[0]
print(N)

5


In [9]:
print("a_centered_sp / (N-1) = ", a_centered_sp / (N-1))

a_centered_sp / (N-1) =  2.0


Задание 4**
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:
https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 


In [12]:
cov_matrix = np.cov(a.T)
print("Ковариационная матрица:")
print(cov_matrix)
print("Значение ковариации = ", cov_matrix[0,1])

Ковариационная матрица:
[[1.  2. ]
 [2.  4.3]]
Значение ковариации =  2.0
